version: '3.8'
services:
    opencats:
      container_name: opencats_test_web
      image: prooph/nginx:www
      ports:
          - "80:80"
          - "443:443"
      volumes_from:
        - opencatsdata
      depends_on:
        opencatsdb:
          condition: service_healthy

    php:
      container_name: opencats_test_php
      image: opencats/php-base:8.2-fpm-alpine
      volumes_from:
        - opencatsdata
      depends_on:
        opencatsdb:
          condition: service_healthy

    opencatsdata:
      container_name: opencats_test_data
      image: busybox
      volumes:
        - ..:/var/www/public
        - ../test/config.php:/var/www/public/config.php
        - ../test/INSTALL_BLOCK:/var/www/public/INSTALL_BLOCK
      command: "true"

    opencatsdb:
      container_name: opencats_test_mariadb
      image: mariadb:10.11
      ports:
        - 3306
      environment:
        - MYSQL_ROOT_PASSWORD=dev
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev
        - MYSQL_DATABASE=cats_test
      volumes:
        - ../test/data/:/test/data/
        - ../test/scripts/:/test/scripts
        - ../test/data/test.sql:/docker-entrypoint-initdb.d/000_initDB.sql
        - ../test/data/securityTests.sql:/docker-entrypoint-initdb.d/001_addUsers.sql
      healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        interval: 10s
        timeout: 5s
        retries: 5

    integrationtestdb:
      image: mariadb:10.11
      ports:
        - 3307:3306
      environment:
        - MYSQL_ROOT_PASSWORD=dev
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev
        - MYSQL_DATABASE=cats_integrationtest
      healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        interval: 10s
        timeout: 5s
        retries: 5

    selenium:
      container_name: selenium_test
      image: selenium/standalone-chrome:latest
      environment:
        - SE_NODE_MAX_SESSIONS=2
      ports:
        - 4444
      shm_size: '2gb'
