export const MODERN_JSON_FORMAT = 'modern-json';
export const MODERN_DASHBOARD_PAGE = 'dashboard-my';
export const MODERN_CANDIDATES_PAGE = 'candidates-list';
export const MODERN_CANDIDATE_RESUME_PAGE = 'candidates-view-resume';
export const MODERN_CANDIDATE_SHOW_PAGE = 'candidates-show';
export const MODERN_CANDIDATE_EDIT_PAGE = 'candidates-edit';
export const MODERN_CANDIDATE_ADD_PAGE = 'candidates-add';
export const MODERN_JOBORDERS_PAGE = 'joborders-list';
export const MODERN_JOBORDER_SHOW_PAGE = 'joborders-show';
export const MODERN_JOBORDER_ADD_PAGE = 'joborders-add';
export const MODERN_JOBORDER_ADD_POPUP_PAGE = 'joborders-add-popup';
export const MODERN_JOBORDER_RECRUITER_ALLOCATION_PAGE = 'joborders-recruiter-allocation';
export const MODERN_JOBORDER_PIPELINE_MATRIX_PAGE = 'joborders-pipeline-matrix';
export const MODERN_JOBORDER_EDIT_PAGE = 'joborders-edit';
export const MODERN_COMPANIES_PAGE = 'companies-list';
export const MODERN_COMPANY_SHOW_PAGE = 'companies-show';
export const MODERN_COMPANY_ADD_PAGE = 'companies-add';
export const MODERN_COMPANY_EDIT_PAGE = 'companies-edit';
export const MODERN_CONTACTS_PAGE = 'contacts-list';
export const MODERN_CONTACT_COLD_CALL_LIST_PAGE = 'contacts-cold-call-list';
export const MODERN_CONTACT_SHOW_PAGE = 'contacts-show';
export const MODERN_CONTACT_ADD_PAGE = 'contacts-add';
export const MODERN_CONTACT_EDIT_PAGE = 'contacts-edit';
export const MODERN_ACTIVITY_PAGE = 'activity-list';
export const MODERN_CALENDAR_PAGE = 'calendar-workspace';
export const MODERN_LISTS_PAGE = 'lists-manage';
export const MODERN_LISTS_DETAIL_PAGE = 'lists-detail';
export const MODERN_REPORTS_PAGE = 'reports-launcher';
export const MODERN_REPORTS_CUSTOMER_DASHBOARD_PAGE = 'reports-customer-dashboard';
export const MODERN_REPORTS_GRAPH_VIEW_PAGE = 'reports-graph-view';
export const MODERN_GDPR_REQUESTS_PAGE = 'gdpr-requests';
export const MODERN_SOURCING_PAGE = 'sourcing-workspace';
export const MODERN_QUEUE_PAGE = 'queue-workspace';
export const MODERN_GRAPHS_PAGE = 'graphs-workspace';
export const MODERN_HOME_OVERVIEW_PAGE = 'home-overview';
export const MODERN_HOME_INBOX_PAGE = 'home-inbox';
export const MODERN_HOME_MYNOTES_PAGE = 'home-mynotes';
export const MODERN_HOME_QUICKSEARCH_PAGE = 'home-quicksearch';
export const MODERN_IMPORT_LAUNCHER_PAGE = 'import-launcher';
export const MODERN_SETTINGS_ADMINISTRATION_PAGE = 'settings-administration';
export const MODERN_SETTINGS_MYPROFILE_PAGE = 'settings-myprofile';
export const MODERN_SETTINGS_MYPROFILE_CHANGE_PASSWORD_PAGE = 'settings-myprofile-change-password';
export const MODERN_SETTINGS_LOGIN_ACTIVITY_PAGE = 'settings-login-activity';
export const MODERN_SETTINGS_EMAIL_TEMPLATES_PAGE = 'settings-email-templates';
export const MODERN_SETTINGS_GDPR_SETTINGS_PAGE = 'settings-gdpr-settings';
export const MODERN_SETTINGS_REJECTION_REASONS_PAGE = 'settings-rejection-reasons';
export const MODERN_SETTINGS_TAGS_PAGE = 'settings-tags';
export const MODERN_SETTINGS_ROLE_PAGE_PERMISSIONS_PAGE = 'settings-role-page-permissions';
export const MODERN_SETTINGS_SCHEMA_MIGRATIONS_PAGE = 'settings-schema-migrations';
export const MODERN_SETTINGS_VIEW_ITEM_HISTORY_PAGE = 'settings-view-item-history';
export const MODERN_SETTINGS_MANAGE_USERS_PAGE = 'settings-manage-users';
export const MODERN_SETTINGS_ADD_USER_PAGE = 'settings-add-user';
export const MODERN_SETTINGS_EDIT_USER_PAGE = 'settings-edit-user';
export const MODERN_SETTINGS_SHOW_USER_PAGE = 'settings-show-user';
export const MODERN_SETTINGS_EMAIL_SETTINGS_PAGE = 'settings-email-settings';
export const MODERN_SETTINGS_FEEDBACK_SETTINGS_PAGE = 'settings-feedback-settings';
export const MODERN_SETTINGS_FORCE_EMAIL_PAGE = 'settings-force-email';
export const MODERN_SETTINGS_GOOGLE_OIDC_SETTINGS_PAGE = 'settings-google-oidc-settings';
export const MODERN_SETTINGS_DELETE_USER_PAGE = 'settings-delete-user';
export const MODERN_SETTINGS_CUSTOMIZE_CALENDAR_PAGE = 'settings-customize-calendar';
export const MODERN_SETTINGS_EEO_PAGE = 'settings-eeo';
export const MODERN_SETTINGS_TALENT_FIT_FLOW_SETTINGS_PAGE = 'settings-talent-fit-flow-settings';
export const MODERN_SETTINGS_NEW_INSTALL_PASSWORD_PAGE = 'settings-new-install-password';
export const MODERN_SETTINGS_NEW_SITE_NAME_PAGE = 'settings-new-site-name';
export const MODERN_SETTINGS_EMAIL_SETTINGS_CONTRACT_KEY = 'settings.emailSettings.v1';
export const MODERN_SETTINGS_EMAIL_SETTINGS_MUTATION_CONTRACT_KEY = 'settings.emailSettings.mutation.v1';
export const MODERN_SETTINGS_FEEDBACK_SETTINGS_CONTRACT_KEY = 'settings.feedbackSettings.v1';
export const MODERN_SETTINGS_FEEDBACK_SETTINGS_MUTATION_CONTRACT_KEY = 'settings.feedbackSettings.mutation.v1';
export const MODERN_SETTINGS_FORCE_EMAIL_CONTRACT_KEY = 'settings.forceEmail.v1';
export const MODERN_SETTINGS_FORCE_EMAIL_MUTATION_CONTRACT_KEY = 'settings.forceEmail.mutation.v1';
export const MODERN_SETTINGS_GOOGLE_OIDC_SETTINGS_CONTRACT_KEY = 'settings.googleOIDCSettings.v1';
export const MODERN_SETTINGS_GOOGLE_OIDC_SETTINGS_MUTATION_CONTRACT_KEY = 'settings.googleOIDCSettings.mutation.v1';
export const MODERN_SETTINGS_DELETE_USER_CONTRACT_KEY = 'settings.deleteUser.v1';
export const MODERN_SETTINGS_DELETE_USER_MUTATION_CONTRACT_KEY = 'settings.deleteUser.mutation.v1';
export const MODERN_SETTINGS_CUSTOMIZE_CALENDAR_CONTRACT_KEY = 'settings.customizeCalendar.v1';
export const MODERN_SETTINGS_CUSTOMIZE_CALENDAR_MUTATION_CONTRACT_KEY = 'settings.customizeCalendar.mutation.v1';
export const MODERN_SETTINGS_EEO_CONTRACT_KEY = 'settings.eeo.v1';
export const MODERN_SETTINGS_EEO_MUTATION_CONTRACT_KEY = 'settings.eeo.mutation.v1';
export const MODERN_SETTINGS_TALENT_FIT_FLOW_SETTINGS_CONTRACT_KEY = 'settings.talentFitFlowSettings.v1';
export const MODERN_SETTINGS_TALENT_FIT_FLOW_SETTINGS_MUTATION_CONTRACT_KEY = 'settings.talentFitFlowSettings.mutation.v1';
export const MODERN_SETTINGS_NEW_INSTALL_PASSWORD_CONTRACT_KEY = 'settings.newInstallPassword.v1';
export const MODERN_SETTINGS_NEW_INSTALL_PASSWORD_MUTATION_CONTRACT_KEY = 'settings.newInstallPassword.mutation.v1';
export const MODERN_SETTINGS_NEW_SITE_NAME_CONTRACT_KEY = 'settings.newSiteName.v1';
export const MODERN_SETTINGS_NEW_SITE_NAME_MUTATION_CONTRACT_KEY = 'settings.newSiteName.mutation.v1';
export const MODERN_LOGIN_PAGE = 'login-workspace';
export const MODERN_RSS_JOBORDERS_PAGE = 'rss-joborders';
export const MODERN_KPIS_PAGE = 'kpis-list';
export const MODERN_KPIS_DETAILS_PAGE = 'kpis-details';
export const MODERN_CONTRACT_VERSION = 1;

export type ModernRequestParams = {
  module: string;
  action: string;
  modernPage: string;
  query?: URLSearchParams;
};

export function buildModernJSONRequestQuery(params: ModernRequestParams): URLSearchParams {
  const next = new URLSearchParams(params.query ?? undefined);
  next.set('m', params.module);
  next.set('a', params.action);
  next.set('format', MODERN_JSON_FORMAT);
  next.set('modernPage', params.modernPage);
  next.set('contractVersion', String(MODERN_CONTRACT_VERSION));

  /* Explicitly bypass modern shell routing for data requests. */
  next.set('ui', 'legacy');

  return next;
}
